/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/models/gltf/iphone17.glb --types --keepmeshes --keepmaterials --keepnames --keepgroups --output ../engine-react/src/features/canvas/components/Iphone/model/iphone.base.model.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import modelPath from '@iphone17pro-lp/engine-assets/models/gltf/iphone17.glb';

type GLTFResult = GLTF & {
  nodes: {
    MSH_Antenna_Bands: THREE.Mesh;
    MSH_Antenna_Window: THREE.Mesh;
    MSH_Button_Action: THREE.Mesh;
    MSH_Button_Camera_Control: THREE.Mesh;
    MSH_Button_Side: THREE.Mesh;
    MSH_Button_Volume_Down: THREE.Mesh;
    MSH_Button_Volume_Up: THREE.Mesh;
    MSH_Camera_Main_Front: THREE.Mesh;
    MSH_Camera_Main_Mirror: THREE.Mesh;
    MSH_Camera_Telephoto_Front: THREE.Mesh;
    MSH_Camera_Telephoto_Mirror: THREE.Mesh;
    MSH_Camera_Wide_Front: THREE.Mesh;
    MSH_Camera_Wide_Mirror: THREE.Mesh;
    MSH_Camera_Plateau_Forged: THREE.Mesh;
    MSH_Camera_Main_Body: THREE.Mesh;
    MSH_Camera_Main_Lens: THREE.Mesh;
    MSH_Camera_Selfie_Attach: THREE.Mesh;
    MSH_Camera_Selfie_Body: THREE.Mesh;
    MSH_Camera_Selfie_Lens: THREE.Mesh;
    MSH_Camera_Selfie_Mirror: THREE.Mesh;
    MSH_Camera_Telephoto_Body: THREE.Mesh;
    MSH_Camera_Telephoto_Lens: THREE.Mesh;
    MSH_Camera_Telephoto_Lens_Glass: THREE.Mesh;
    MSH_Camera_Wide_Body: THREE.Mesh;
    MSH_Camera_Wide_Lens: THREE.Mesh;
    MHS_Camera_Led: THREE.Mesh;
    MHS_Camera_Lidar: THREE.Mesh;
    MSH_Chassis_Screws: THREE.Mesh;
    MSH_Chassis_Speakers: THREE.Mesh;
    M_Body_main002: THREE.Mesh;
    M_Body_main002_1: THREE.Mesh;
    M_Body_main002_2: THREE.Mesh;
    MSH_Rear_Ceramic_Pane: THREE.Mesh;
    MSH_Rear_Logo: THREE.Mesh;
    MHS_Screen_Border: THREE.Mesh;
    MHS_Screen_Display: THREE.Mesh;
    GEO_Screen_Glass: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(modelPath) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group name="GRP_Iphone_17">
        <group name="GRP_Antenna_System">
          <mesh
            name="MSH_Antenna_Bands"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Antenna_Bands.geometry}
            material={nodes.MSH_Antenna_Bands.material}
          />
          <mesh
            name="MSH_Antenna_Window"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Antenna_Window.geometry}
            material={nodes.MSH_Antenna_Window.material}
          />
        </group>
        <group name="GRP_Button_System">
          <mesh
            name="MSH_Button_Action"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Button_Action.geometry}
            material={nodes.MSH_Button_Action.material}
          />
          <mesh
            name="MSH_Button_Camera_Control"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Button_Camera_Control.geometry}
            material={nodes.MSH_Button_Camera_Control.material}
          />
          <mesh
            name="MSH_Button_Side"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Button_Side.geometry}
            material={nodes.MSH_Button_Side.material}
          />
          <mesh
            name="MSH_Button_Volume_Down"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Button_Volume_Down.geometry}
            material={nodes.MSH_Button_Volume_Down.material}
          />
          <mesh
            name="MSH_Button_Volume_Up"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Button_Volume_Up.geometry}
            material={nodes.MSH_Button_Volume_Up.material}
          />
        </group>
        <group name="GRP_Camera_Plateau">
          <group name="GRP_Camera_Main_Cover">
            <mesh
              name="MSH_Camera_Main_Front"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Main_Front.geometry}
              material={nodes.MSH_Camera_Main_Front.material}
            />
            <mesh
              name="MSH_Camera_Main_Mirror"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Main_Mirror.geometry}
              material={nodes.MSH_Camera_Main_Mirror.material}
            />
          </group>
          <group name="GRP_Camera_Telephoto_Cover">
            <mesh
              name="MSH_Camera_Telephoto_Front"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Telephoto_Front.geometry}
              material={nodes.MSH_Camera_Telephoto_Front.material}
            />
            <mesh
              name="MSH_Camera_Telephoto_Mirror"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Telephoto_Mirror.geometry}
              material={nodes.MSH_Camera_Telephoto_Mirror.material}
            />
          </group>
          <group name="GRP_Camera_Wide_Cover">
            <mesh
              name="MSH_Camera_Wide_Front"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Wide_Front.geometry}
              material={nodes.MSH_Camera_Wide_Front.material}
            />
            <mesh
              name="MSH_Camera_Wide_Mirror"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Wide_Mirror.geometry}
              material={nodes.MSH_Camera_Wide_Mirror.material}
            />
          </group>
          <mesh
            name="MSH_Camera_Plateau_Forged"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Camera_Plateau_Forged.geometry}
            material={nodes.MSH_Camera_Plateau_Forged.material}
          />
        </group>
        <group name="GRP_Camera_System">
          <group name="GRP_Camera_Main">
            <mesh
              name="MSH_Camera_Main_Body"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Main_Body.geometry}
              material={nodes.MSH_Camera_Main_Body.material}
            />
            <mesh
              name="MSH_Camera_Main_Lens"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Main_Lens.geometry}
              material={nodes.MSH_Camera_Main_Lens.material}
            />
          </group>
          <group name="GRP_Camera_Selfie">
            <mesh
              name="MSH_Camera_Selfie_Attach"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Selfie_Attach.geometry}
              material={nodes.MSH_Camera_Selfie_Attach.material}
            />
            <mesh
              name="MSH_Camera_Selfie_Body"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Selfie_Body.geometry}
              material={nodes.MSH_Camera_Selfie_Body.material}
            />
            <mesh
              name="MSH_Camera_Selfie_Lens"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Selfie_Lens.geometry}
              material={nodes.MSH_Camera_Selfie_Lens.material}
            />
            <mesh
              name="MSH_Camera_Selfie_Mirror"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Selfie_Mirror.geometry}
              material={nodes.MSH_Camera_Selfie_Mirror.material}
            />
          </group>
          <group name="GRP_Camera_Telephoto">
            <mesh
              name="MSH_Camera_Telephoto_Body"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Telephoto_Body.geometry}
              material={nodes.MSH_Camera_Telephoto_Body.material}
            />
            <mesh
              name="MSH_Camera_Telephoto_Lens"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Telephoto_Lens.geometry}
              material={nodes.MSH_Camera_Telephoto_Lens.material}
            />
            <mesh
              name="MSH_Camera_Telephoto_Lens_Glass"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Telephoto_Lens_Glass.geometry}
              material={nodes.MSH_Camera_Telephoto_Lens_Glass.material}
            />
          </group>
          <group name="GRP_Camera_Wide">
            <mesh
              name="MSH_Camera_Wide_Body"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Wide_Body.geometry}
              material={nodes.MSH_Camera_Wide_Body.material}
            />
            <mesh
              name="MSH_Camera_Wide_Lens"
              castShadow
              receiveShadow
              geometry={nodes.MSH_Camera_Wide_Lens.geometry}
              material={nodes.MSH_Camera_Wide_Lens.material}
            />
          </group>
          <mesh
            name="MHS_Camera_Led"
            castShadow
            receiveShadow
            geometry={nodes.MHS_Camera_Led.geometry}
            material={nodes.MHS_Camera_Led.material}
          />
          <mesh
            name="MHS_Camera_Lidar"
            castShadow
            receiveShadow
            geometry={nodes.MHS_Camera_Lidar.geometry}
            material={nodes.MHS_Camera_Lidar.material}
          />
        </group>
        <group name="GRP_Chassis_Main">
          <mesh
            name="MSH_Chassis_Screws"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Chassis_Screws.geometry}
            material={nodes.MSH_Chassis_Screws.material}
          />
          <mesh
            name="MSH_Chassis_Speakers"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Chassis_Speakers.geometry}
            material={nodes.MSH_Chassis_Speakers.material}
          />
          <group name="MSH_Chassis_Unibody_Frame" scale={2.06}>
            <mesh
              name="M_Body_main002"
              castShadow
              receiveShadow
              geometry={nodes.M_Body_main002.geometry}
              material={nodes.M_Body_main002.material}
            />
            <mesh
              name="M_Body_main002_1"
              castShadow
              receiveShadow
              geometry={nodes.M_Body_main002_1.geometry}
              material={nodes.M_Body_main002_1.material}
            />
            <mesh
              name="M_Body_main002_2"
              castShadow
              receiveShadow
              geometry={nodes.M_Body_main002_2.geometry}
              material={nodes.M_Body_main002_2.material}
            />
          </group>
        </group>
        <group name="GRP_Rear_Assembly">
          <mesh
            name="MSH_Rear_Ceramic_Pane"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Rear_Ceramic_Pane.geometry}
            material={nodes.MSH_Rear_Ceramic_Pane.material}
          />
          <mesh
            name="MSH_Rear_Logo"
            castShadow
            receiveShadow
            geometry={nodes.MSH_Rear_Logo.geometry}
            material={nodes.MSH_Rear_Logo.material}
          />
        </group>
        <group name="GRP_Screen_System">
          <mesh
            name="MHS_Screen_Border"
            castShadow
            receiveShadow
            geometry={nodes.MHS_Screen_Border.geometry}
            material={nodes.MHS_Screen_Border.material}
          />
          <mesh
            name="MHS_Screen_Display"
            castShadow
            receiveShadow
            geometry={nodes.MHS_Screen_Display.geometry}
            material={nodes.MHS_Screen_Display.material}
          />
          <group name="MHS_Screen_Glass" scale={2.06}>
            <mesh
              name="GEO_Screen_Glass"
              castShadow
              receiveShadow
              geometry={nodes.GEO_Screen_Glass.geometry}
              material={nodes.GEO_Screen_Glass.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);
