/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/models/gltf/iphone17.glb --types --keepmeshes --keepmaterials --keepnames --keepgroups --output ../engine-react/src/features/canvas/components/Iphone/model/iphone.base.model.tsx 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import modelPath from '@iphone17pro-lp/engine-assets/models/gltf/iphone17.glb';

type GLTFResult = GLTF & {
  nodes: {
    Body_main: THREE.Mesh;
    Body_detail: THREE.Mesh;
    Button: THREE.Mesh;
    Button_wire: THREE.Mesh;
    BackGlass: THREE.Mesh;
    BackCameraTop_back: THREE.Mesh;
    BackCameraTop_front: THREE.Mesh;
    BackCameraTop_glass: THREE.Mesh;
    M_BackCameraTop_lens: THREE.Mesh;
    M_BackCameraTop_lens_1: THREE.Mesh;
    BackCameraBot_back: THREE.Mesh;
    BackCameraBot_front: THREE.Mesh;
    BackCameraBot_lens: THREE.Mesh;
    BackCameraBot_mirror: THREE.Mesh;
    BackCameraCenter_back: THREE.Mesh;
    BackCameraCenter_front: THREE.Mesh;
    BackCameraCenter_glass: THREE.Mesh;
    BackCameraCenter_lens: THREE.Mesh;
    M_CameraFront: THREE.Mesh;
    M_CameraFront_1: THREE.Mesh;
    Led_back: THREE.Mesh;
    Led_front: THREE.Mesh;
    Lidar: THREE.Mesh;
    Screen_border: THREE.Mesh;
    Screen_display: THREE.Mesh;
    Screen_glass: THREE.Mesh;
    Screws: THREE.Mesh;
    Speakers: THREE.Mesh;
    CameraAttach_front: THREE.Mesh;
    CameraAttach_back: THREE.Mesh;
    Body_back: THREE.Mesh;
  };
  materials: {
    Aluminum: THREE.MeshStandardMaterial;
    Plastic_antena: THREE.MeshStandardMaterial;
    Tint_back_glass: THREE.MeshStandardMaterial;
    Metal_Screw: THREE.MeshStandardMaterial;
    Camera_filter: THREE.MeshPhysicalMaterial;
    Frame: THREE.MeshStandardMaterial;
    Mirror_filter: THREE.MeshStandardMaterial;
    g: THREE.MeshStandardMaterial;
    Lens: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    Plastic_LED: THREE.MeshStandardMaterial;
    Display: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(modelPath) as unknown as GLTFResult;
  materials.Mirror_filter.envMapIntensity = 1; // Ajuste o valor conforme desejar

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Body_main"
          geometry={nodes.Body_main.geometry}
          material={materials.Aluminum}
          scale={2.06}
        />
        <mesh
          name="Body_detail"
          geometry={nodes.Body_detail.geometry}
          material={materials.Plastic_antena}
          scale={2.06}
        />
        <mesh
          name="Button"
          geometry={nodes.Button.geometry}
          material={materials.Tint_back_glass}
          scale={2.06}
        />
        <mesh
          name="Button_wire"
          geometry={nodes.Button_wire.geometry}
          material={materials.Metal_Screw}
          scale={2.06}
        />
        <mesh
          name="BackGlass"
          geometry={nodes.BackGlass.geometry}
          material={materials.Tint_back_glass}
          scale={2.06}
        />
        <group name="BackCameraTop" scale={2.06}>
          <mesh
            name="BackCameraTop_back"
            geometry={nodes.BackCameraTop_back.geometry}
            material={materials.Camera_filter}
          />
          <mesh
            name="BackCameraTop_front"
            geometry={nodes.BackCameraTop_front.geometry}
            material={materials.Frame}
          />
          <mesh
            name="BackCameraTop_glass"
            geometry={nodes.BackCameraTop_glass.geometry}
            material={materials.Mirror_filter}
          />
          <group name="BackCameraTop_lens">
            <mesh
              name="M_BackCameraTop_lens"
              geometry={nodes.M_BackCameraTop_lens.geometry}
              material={materials.g}
            />
            <mesh
              name="M_BackCameraTop_lens_1"
              geometry={nodes.M_BackCameraTop_lens_1.geometry}
              material={materials.Lens}
            />
          </group>
        </group>
        <group name="BackCameraBot" scale={2.06}>
          <mesh
            name="BackCameraBot_back"
            geometry={nodes.BackCameraBot_back.geometry}
            material={materials.Camera_filter}
          />
          <mesh
            name="BackCameraBot_front"
            geometry={nodes.BackCameraBot_front.geometry}
            material={materials.Frame}
          />
          <mesh
            name="BackCameraBot_lens"
            geometry={nodes.BackCameraBot_lens.geometry}
            material={materials.Lens}
          />
          <mesh
            name="BackCameraBot_mirror"
            geometry={nodes.BackCameraBot_mirror.geometry}
            material={materials.Mirror_filter}
          />
        </group>
        <group name="BackCameraCenter" scale={2.06}>
          <mesh
            name="BackCameraCenter_back"
            geometry={nodes.BackCameraCenter_back.geometry}
            material={materials.Camera_filter}
          />
          <mesh
            name="BackCameraCenter_front"
            geometry={nodes.BackCameraCenter_front.geometry}
            material={materials.Frame}
          />
          <mesh
            name="BackCameraCenter_glass"
            geometry={nodes.BackCameraCenter_glass.geometry}
            material={materials.Mirror_filter}
          />
          <mesh
            name="BackCameraCenter_lens"
            geometry={nodes.BackCameraCenter_lens.geometry}
            material={materials.Lens}
          />
        </group>
        <group name="CameraFront" scale={2.06}>
          <mesh
            name="M_CameraFront"
            geometry={nodes.M_CameraFront.geometry}
            material={materials.Lens}
          />
          <mesh
            name="M_CameraFront_1"
            geometry={nodes.M_CameraFront_1.geometry}
            material={materials.Camera_filter}
          />
        </group>
        <group name="Led" scale={2.06}>
          <mesh name="Led_back" geometry={nodes.Led_back.geometry} material={materials.material} />
          <mesh
            name="Led_front"
            geometry={nodes.Led_front.geometry}
            material={materials.Plastic_LED}
          />
        </group>
        <mesh
          name="Lidar"
          geometry={nodes.Lidar.geometry}
          material={materials.Frame}
          scale={2.06}
        />
        <group name="Screen" scale={2.06}>
          <mesh
            name="Screen_border"
            geometry={nodes.Screen_border.geometry}
            material={materials.Frame}
          />
          <mesh
            name="Screen_display"
            geometry={nodes.Screen_display.geometry}
            material={materials.Display}
          />
          <mesh
            name="Screen_glass"
            geometry={nodes.Screen_glass.geometry}
            material={materials.Glass}
          />
        </group>
        <mesh
          name="Screws"
          geometry={nodes.Screws.geometry}
          material={materials.Metal_Screw}
          scale={2.06}
        />
        <mesh
          name="Speakers"
          geometry={nodes.Speakers.geometry}
          material={materials.Metal_Screw}
          scale={2.06}
        />
        <mesh
          name="CameraAttach_front"
          geometry={nodes.CameraAttach_front.geometry}
          material={materials.Aluminum}
          scale={2.06}
        />
        <mesh
          name="CameraAttach_back"
          geometry={nodes.CameraAttach_back.geometry}
          material={materials.Aluminum}
          scale={2.06}
        />
        <mesh
          name="Body_back"
          geometry={nodes.Body_back.geometry}
          material={materials.Aluminum}
          scale={2.06}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);
