/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'
// Import the asset directly from the workspace package
// This requires the bundler to handle the asset path resolution
import modelPath from '@iphone17pro-lp/engine-assets/src/models/iphone17.glb'

type GLTFResult = GLTF & {
  nodes: {
    M_Body_main: THREE.Mesh
    M_Body_main_1: THREE.Mesh
    M_Body_main_2: THREE.Mesh
    M_Body_main_3: THREE.Mesh
    Body_wire: THREE.Mesh
    Button: THREE.Mesh
    Button_wire: THREE.Mesh
    BackGlass_back: THREE.Mesh
    BackGlass_glass: THREE.Mesh
    BackGlass_logo: THREE.Mesh
    BackCameraTop_back: THREE.Mesh
    BackCameraTop_front: THREE.Mesh
    M_BackCameraTop_glass: THREE.Mesh
    M_BackCameraTop_glass_1: THREE.Mesh
    M_BackCameraTop_lens: THREE.Mesh
    M_BackCameraTop_lens_1: THREE.Mesh
    BackCameraBot_back: THREE.Mesh
    BackCameraBot_front: THREE.Mesh
    BackCameraBot_lens: THREE.Mesh
    M_BackCameraBot_mirror: THREE.Mesh
    M_BackCameraBot_mirror_1: THREE.Mesh
    BackCameraCenter_back: THREE.Mesh
    BackCameraCenter_front: THREE.Mesh
    M_BackCameraCenter_glass: THREE.Mesh
    M_BackCameraCenter_glass_1: THREE.Mesh
    BackCameraCenter_lens: THREE.Mesh
    M_CameraFront: THREE.Mesh
    M_CameraFront_1: THREE.Mesh
    Led_back: THREE.Mesh
    Led_front: THREE.Mesh
    Lidar: THREE.Mesh
    Screen_border: THREE.Mesh
    Screen_display: THREE.Mesh
    Screen_glass: THREE.Mesh
    Screws: THREE.Mesh
    Speakers: THREE.Mesh
  }
  materials: {
    Aluminum: THREE.MeshStandardMaterial
    Camera_filter: THREE.MeshStandardMaterial
    Metal_Screw: THREE.MeshStandardMaterial
    Plastic_USB_port: THREE.MeshStandardMaterial
    Plastic_antena: THREE.MeshStandardMaterial
    Tint_back_glass: THREE.MeshStandardMaterial
    Frosted_glass: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    Frame: THREE.MeshStandardMaterial
    Sapphire_miror: THREE.MeshStandardMaterial
    Mirror_filter: THREE.MeshStandardMaterial
    Lens: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Plastic_LED: THREE.MeshStandardMaterial
    Display: THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group']) {
  // Fixed type error by casting to unknown first
  const { nodes, materials } = useGLTF(modelPath) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Body_wire"
        geometry={nodes.Body_wire.geometry}
        material={materials.Plastic_antena}
      />
      <mesh name="Button" geometry={nodes.Button.geometry} material={materials.Tint_back_glass} />
      <mesh
        name="Button_wire"
        geometry={nodes.Button_wire.geometry}
        material={materials.Metal_Screw}
      />
      <mesh name="Lidar" geometry={nodes.Lidar.geometry} material={materials.Frame} />
      <mesh name="Screws" geometry={nodes.Screws.geometry} material={materials.Metal_Screw} />
      <mesh name="Speakers" geometry={nodes.Speakers.geometry} material={materials.Metal_Screw} />
      <mesh
        name="M_Body_main"
        geometry={nodes.M_Body_main.geometry}
        material={materials.Aluminum}
      />
      <mesh
        name="M_Body_main_1"
        geometry={nodes.M_Body_main_1.geometry}
        material={materials.Camera_filter}
      />
      <mesh
        name="M_Body_main_2"
        geometry={nodes.M_Body_main_2.geometry}
        material={materials.Metal_Screw}
      />
      <mesh
        name="M_Body_main_3"
        geometry={nodes.M_Body_main_3.geometry}
        material={materials.Plastic_USB_port}
      />
      <mesh
        name="BackGlass_back"
        geometry={nodes.BackGlass_back.geometry}
        material={materials.Frosted_glass}
      />
      <mesh
        name="BackGlass_glass"
        geometry={nodes.BackGlass_glass.geometry}
        material={materials.Tint_back_glass}
      />
      <mesh
        name="BackGlass_logo"
        geometry={nodes.BackGlass_logo.geometry}
        material={materials.Glass}
      />
      <mesh
        name="BackCameraTop_back"
        geometry={nodes.BackCameraTop_back.geometry}
        material={materials.Camera_filter}
      />
      <mesh
        name="BackCameraTop_front"
        geometry={nodes.BackCameraTop_front.geometry}
        material={materials.Frame}
      />
      <mesh
        name="M_BackCameraTop_glass"
        geometry={nodes.M_BackCameraTop_glass.geometry}
        material={materials.Sapphire_miror}
      />
      <mesh
        name="M_BackCameraTop_glass_1"
        geometry={nodes.M_BackCameraTop_glass_1.geometry}
        material={materials.Mirror_filter}
      />
      <mesh
        name="M_BackCameraTop_lens"
        geometry={nodes.M_BackCameraTop_lens.geometry}
        material={materials.Sapphire_miror}
      />
      <mesh
        name="M_BackCameraTop_lens_1"
        geometry={nodes.M_BackCameraTop_lens_1.geometry}
        material={materials.Lens}
      />
      <mesh
        name="BackCameraBot_back"
        geometry={nodes.BackCameraBot_back.geometry}
        material={materials.Camera_filter}
      />
      <mesh
        name="BackCameraBot_front"
        geometry={nodes.BackCameraBot_front.geometry}
        material={materials.Frame}
      />
      <mesh
        name="BackCameraBot_lens"
        geometry={nodes.BackCameraBot_lens.geometry}
        material={materials.Lens}
      />
      <mesh
        name="M_BackCameraBot_mirror"
        geometry={nodes.M_BackCameraBot_mirror.geometry}
        material={materials.Sapphire_miror}
      />
      <mesh
        name="M_BackCameraBot_mirror_1"
        geometry={nodes.M_BackCameraBot_mirror_1.geometry}
        material={materials.Mirror_filter}
      />
      <mesh
        name="BackCameraCenter_back"
        geometry={nodes.BackCameraCenter_back.geometry}
        material={materials.Camera_filter}
      />
      <mesh
        name="BackCameraCenter_front"
        geometry={nodes.BackCameraCenter_front.geometry}
        material={materials.Frame}
      />
      <mesh
        name="BackCameraCenter_lens"
        geometry={nodes.BackCameraCenter_lens.geometry}
        material={materials.Lens}
      />
      <mesh
        name="M_BackCameraCenter_glass"
        geometry={nodes.M_BackCameraCenter_glass.geometry}
        material={materials.Mirror_filter}
      />
      <mesh
        name="M_BackCameraCenter_glass_1"
        geometry={nodes.M_BackCameraCenter_glass_1.geometry}
        material={materials.Sapphire_miror}
      />
      <mesh
        name="M_CameraFront"
        geometry={nodes.M_CameraFront.geometry}
        material={materials.Lens}
      />
      <mesh
        name="M_CameraFront_1"
        geometry={nodes.M_CameraFront_1.geometry}
        material={materials.Camera_filter}
      />
      <mesh name="Led_back" geometry={nodes.Led_back.geometry} material={materials.material} />
      <mesh name="Led_front" geometry={nodes.Led_front.geometry} material={materials.Plastic_LED} />
      <mesh
        name="Screen_border"
        geometry={nodes.Screen_border.geometry}
        material={materials.Frame}
      />
      <mesh
        name="Screen_display"
        geometry={nodes.Screen_display.geometry}
        material={materials.Display}
      />
      <mesh name="Screen_glass" geometry={nodes.Screen_glass.geometry} material={materials.Glass} />
    </group>
  )
}

useGLTF.preload(modelPath)